version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 5
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 5
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
