= Draw.io Export

Export Draw.io diagrams using docker

== Features

* Recursive export
* Partial export (newer, or based on git reference)
* Additional export formats with link extraction

== Supported Export formats

* **draw.io** export formats : jpg, pdf, png, svg, vsdx, and xml
* **drawio-exporter** additional formats
** adoc - Export in png and create an additional asciidoc file (with support external links).
** md - Export in png and create an additional markdown file (with support external links).

== Supported fonts formats

Check installed fonts list from https://github.com/rlespinasse/docker-drawio-desktop-headless[drawio-desktop-headless] docker base image.

== Installation

[source,bash]
----
docker pull rlespinasse/drawio-export
----

== Usage

.Print the available options
[source,bash]
----
docker run -it rlespinasse/drawio-export --help
----

.Simple run with default options
[source,bash]
----
$ cd directory-with-drawio-files
$ docker run -it -v $(pwd):/data rlespinasse/drawio-export
+ export file : ./file1.drawio
++ export page 1 : Page-1
+++ generate pdf file
++ export page 2 : Page 2
+++ generate pdf file
----

== Build on top of

* https://github.com/rlespinasse/docker-drawio-desktop-headless[**rlespinasse/drawio-export-headless**] as base docker image to use Draw.io Desktop for its command lines,
* https://github.com/rlespinasse/drawio-exporter[**drawio-exporter**] as backend for export capabilities.

== Used by

* GitHub Action https://github.com/rlespinasse/drawio-export-action[**drawio-export-action**] : which is build on top of **drawio-export** docker image.

== Contributing

Pull requests are welcome.
For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.
