= Draw.io Export

Export Draw.io diagrams using command line / docker

== Supported Export formats

* **draw.io** export formats
** pdf
** png
** jpg
** svg
** vsdx
* **drawio-export** additional formats
** adoc - Export in png and create an additional asciidoc file (with support external links).

== Installation

[source,bash]
----
docker pull rlespinasse/drawio-export
----

== Usage

[source,bash]
----
$ cd directory-with-drawio-files
$ docker run -it -v $(pwd):/data rlespinasse/drawio-export
prepare './export' folder
cleanup './export/file-*' content
export page 1 - ./file1.drawio
./file1.drawio -> ./export/file1-Page-1.pdf
export page 2 - ./file1.drawio
./file1.drawio -> ./export/file1-Page-2.pdf
----

You can override default configuration

* `DRAWIO_EXPORT_FILEEXT`: extention of exported files (default `pdf`)
* `DRAWIO_EXPORT_CLI_OPTIONS`: draw.io cli options to export (default `--crop`)
* `DRAWIO_EXPORT_FOLDER`: folder of exported files, with tree preservation (default `export`)

For example, export draw.io diagrams as PNG with transparent background

[source,bash]
----
$ cd directory-with-drawio-files
$ docker run -it -v $(pwd):/data -e DRAWIO_EXPORT_FILEEXT=png -e DRAWIO_EXPORT_FILEEXT="-t -b 1" -e DRAWIO_EXPORT_FOLDER=images rlespinasse/drawio-export
prepare './images' folder
cleanup './images/file-*' content
export page 1 - ./file1.drawio
./file1.drawio -> ./export/file1-Page-1.png
export page 2 - ./file1.drawio
./file1.drawio -> ./export/file1-Page-2.png
----

You can print the available options with

[source,bash]
----
docker run -it rlespinasse/drawio-export --help
----

== Integrations

.GitHub Action : Export and commit your draw.io files
[%collapsible]
====
..github/workflows/drawio-export.yaml
[source,yaml]
----
name: Keep draw.io export synchronized
on:
  push:
    branches:
      - master
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yaml
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Export drawio files to asciidoctor and png files
        uses: docker://rlespinasse/drawio-export
        env:
          DRAWIO_EXPORT_FILEEXT: adoc
          DEFAULT_DRAWIO_EXPORT_CLI_OPTIONS: -t
          DRAWIO_EXPORT_FOLDER: assets
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: "docs: sync draw.io exported files"
----
====

== Contributing

Pull requests are welcome.
For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.
