---
name: Autoupdate Drawio Exporter

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight (UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: autoupdate-drawio-exporter
  cancel-in-progress: true

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - run: make autoupdate-drawio-exporter
        id: autoupdate-drawio-exporter
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "feat: update to drawio-exporter ${{ steps.autoupdate-drawio-exporter.outputs.release_version }}"
          branch: autoupdate-drawio-exporter
          token: ${{ secrets.GH_TOKEN }}
