---
name: Update Docker Hub information

on:
  release:
    types: [published]
  push:
    branches:
      - v4.x
    paths:
      - DOCKER.md
      - .github/workflows/dockerhub.yaml

permissions: read-all

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Sync information on Docker Hub
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: rlespinasse
          password: ${{ secrets.DOCKER_PASSWORD }}
          readme-filepath: ./DOCKER.md
