---
name: Build And Release

on:
  pull_request:
  push:
    branches:
      - v4.x

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true

    steps:
      # Setup
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0

      - uses: rlespinasse/github-slug-action@ef93b2ea4b6405d06fd8684fc3ff795d262ecae8 # v5.7.0

      - name: Build docker image
        run: make build
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Setup CI for test
        run: make test-ci-setup
        shell: bash

      - name: Test docker image
        run: make test-ci
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Test docker image // Store output logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-docker-image-logs
          path: "tests/output/*.log"
        if: ${{ always() }}

      - name: Test docker image // Store output files
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-docker-image-files
          path: |
            tests/data
            !tests/data/*.drawio
            !tests/data/*/*.drawio
        if: ${{ always() }}

  build-multiarch:
    runs-on: ubuntu-latest

    concurrency:
      group: build-multiarch-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: rlespinasse/github-slug-action@ef93b2ea4b6405d06fd8684fc3ff795d262ecae8 # v5.7.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: "arm64,arm"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build docker image
        run: make build-multiarch
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

  release:
    runs-on: ubuntu-latest

    needs:
      - build
      - build-multiarch

    permissions:
      contents: write
      issues: write
      id-token: write
      packages: write

    concurrency:
      group: release-${{ github.ref }}-${{ github.event_name }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Release this docker image
        uses: rlespinasse/release-that@cb1bc2bf712d0fb87c82867852abb1b5128554fb # v1.16.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
