name: Build And Release

on:
  pull_request:
  push:
    branches:
      - v4.x
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true
    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3

      - uses: rlespinasse/github-slug-action@v4

      # Build and test
      - name: Build docker image
        run: make build
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Test docker image // Run
        id: test-docker-image
        run: |
          make setup-test
          make test
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Test docker image // Store output logs
        uses: actions/upload-artifact@v3
        with:
          name: test-docker-image-logs
          path: "tests/output/*.log"
        if: ${{ failure() }}

  release:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: release-${{ github.ref }}-${{ github.event_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Release this docker image
        uses: rlespinasse/release-that@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
